language: go
sudo: false
services: mongodb
go:
   - 1.6.x
   - 1.7.x
   - 1.8.x
   - 1.9.x
   - 1.10.x
   - 1.11.x
   - tip

script:
  - make test
  - ./proxy.sh -f proxy_test.conf mongo --quiet --eval 'printjson(db.version())'
